GRANT ALL ON SCHEMA_NAME TABLE_NAME TO OWNER_NAME;
GRANT ALL ON ALL TABLES IN SCHEMA TABLE_NAME TO OWNER_NAME;
GRANT ALL ON ALL SEQUENCES IN SCHEMA TABLE_NAME TO OWNER_NAME;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA TABLE_NAME TO OWNER_NAME;
